// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojjrtkhocwpmoxcrqsff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qanJ0a2hvY3dwbW94Y3Jxc2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjE3MTcsImV4cCI6MjA2OTM5NzcxN30.NffZqPg3Uo5QMjYeAshaZ76rvwE5wevMcgLQjmlDQPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});